# Generated by Django 6.0.5 on 2026-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_prenda', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('donde_esta_subido', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('disponible', 'Disponible'), ('vendido', 'Vendido')], default='borrador', max_length=20)),
            ],
        ),
    ]
