# Generated by Django 6.0.5 on 2026-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenda',
            old_name='precio',
            new_name='precio_comprado',
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio_vendido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
