# Generated by Django 6.0.5 on 2026-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_rename_precio_prenda_precio_comprado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='localizador',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
