# Generated by Django 6.0.5 on 2026-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0003_prenda_localizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
